### ISSUE TITLE
Issues to be fixed

### ISSUE THREAD

**Issue by nihitavr** [sen-team8/da-dash#68]
#### Chatroom
- [x] Ui
- [ ] Add file upload
- [x] Ui on fullscreen
- [x] Need to use react custom scroll 
- [x] UI on mobile device is screw*d
- [x] Chatroom ui on dashboard is not showing up
#### Todo
- [x] Add todo with database
- [x] Adjust All, Completed 
- [x] Save todo without editing
- [x] Save todo on press enter
- [x] Need to use react custom scroll 
#### Intranet
- [x] Layout issue on right side when resized
- [x] Intranet height on dashboard
- [x] Add discussion for every lecture folder(level 2)
#### Login
- [x] Enter on login not implemented
